### ISSUE TITLE
Alpha support

### ISSUE THREAD

**Issue by azrafe7** [Justinfront/hxDaedalus-Examples#2]
I'm trying to add alpha support for BasicCanvas, but can't test it on Safari (or mac in general). 
Can you try this (https://dl.dropboxusercontent.com/u/32864004/dev/FPDemo/canvas%20test/DaedalusBitmapPathfinding.html) and see if it works for you?

**Comment by Justinfront** [comment]
I don't much use Safari, it always seemed to take so much discspace, but I have not yet got round to removing it,:)  Comparing with firefox on mac the results are the same.  Safari seems to work fine did not realize there was any alpha issue but glad your looking into it.

**Comment by azrafe7** [comment]
Closing via https://github.com/Justinfront/hxDaedalus/pull/29
