### ISSUE TITLE
GridMaze seem doesn't support touch on mobile web

### ISSUE THREAD

**Issue by nvcken** [Justinfront/hxDaedalus-Examples#3]

**Comment by Justinfront** [comment]
Did you try all versions I guess the main ones - Kha, OpenFL and Heaps? I currently only have borrowed mobile, and internet is not working so can't check all the demos on mobile web. But you should be able to adjust the examples to use different events they are definitely supported by Haxe ecosystem so you can get them working easy enough if they are not currently, but the demos are probably setup for use on desktop browsers, although I know most demos seemed to work fine on my nexus1 and then my nexus6x in the past.  Feel free to provide a pull request with any changes and improvements you make, the purpose of the demos is not to provide a ready made solution but a base for you to expand for your own requirements including specific browser and web browser support.  Will close issue, feel free to post modifications along with aspects your struggling with and will try to help further, but these are demos of the routefinding not finished comercial solutions.
