### ISSUE TITLE
The drawing lacked a short range

### ISSUE THREAD

**Issue by nvcken** [Justinfront/hxDaedalus-Examples#4]
Start here
![screen shot 2018-09-20 at 09 08 22](https://user-images.githubusercontent.com/3489866/45791792-64244080-bcb5-11e8-9ca6-4a43aeae8699.png)
Go to here
![screen shot 2018-09-20 at 09 08 33](https://user-images.githubusercontent.com/3489866/45791795-671f3100-bcb5-11e8-90e2-cbf56dec7635.png)
I mask a orange rectangle to show lacked short range

**Comment by Justinfront** [comment]
Seems to work well on the Kha example, different versions may have slight variations feel free to provide a pull request for a specific version if you make improvements, but as mentioned in the other issue you raised these demos are not comercial products they are just demos for library that can be used for comercial products, the demos are just to help developers with use, and can obviously be improved, if there was a specific problem in the path finding algorithms I would be concerned but seems it's just a detail in a specific version and easy for you to tweak, or use the really good Kha toolkit with hxDaedalus.
https://hxdaedalus.github.io/hxDaedalus-Kha-examples/build/maze/
